// place/placesData.js 파일 내용
const CURATED_PLACES = [
  ...(typeof curated_places_dobong !== 'undefined' ? curated_places_dobong : []),
  ...(typeof curated_places_dongdaemun !== 'undefined' ? curated_places_dongdaemun : []),
  ...(typeof curated_places_dongjak !== 'undefined' ? curated_places_dongjak : []),
  ...(typeof curated_places_eunpyeong !== 'undefined' ? curated_places_eunpyeong : []),
  ...(typeof curated_places_gangbuk !== 'undefined' ? curated_places_gangbuk : []),
  ...(typeof curated_places_gangdong !== 'undefined' ? curated_places_gangdong : []),
  ...(typeof curated_places_gangnam !== 'undefined' ? curated_places_gangnam : []),
  ...(typeof curated_places_gangseo !== 'undefined' ? curated_places_gangseo : []),
  ...(typeof curated_places_geumcheon !== 'undefined' ? curated_places_geumcheon : []),
  ...(typeof curated_places_guro !== 'undefined' ? curated_places_guro : []),
  ...(typeof curated_places_gwanak !== 'undefined' ? curated_places_gwanak : []),
  ...(typeof curated_places_gwangjin !== 'undefined' ? curated_places_gwangjin : []),
  ...(typeof curated_places_jongno !== 'undefined' ? curated_places_jongno : []),
  ...(typeof curated_places_junggu !== 'undefined' ? curated_places_junggu : []),
  ...(typeof curated_places_jungnang !== 'undefined' ? curated_places_jungnang : []),
  ...(typeof curated_places_mapo !== 'undefined' ? curated_places_mapo : []),
  ...(typeof curated_places_nowon !== 'undefined' ? curated_places_nowon : []),
  ...(typeof curated_places_seocho !== 'undefined' ? curated_places_seocho : []),
  ...(typeof curated_places_seodaemun !== 'undefined' ? curated_places_seodaemun : []),
  ...(typeof curated_places_seongbuk !== 'undefined' ? curated_places_seongbuk : []),
  ...(typeof curated_places_seongdong !== 'undefined' ? curated_places_seongdong : []),
  ...(typeof curated_places_songpa !== 'undefined' ? curated_places_songpa : []),
  ...(typeof curated_places_yangcheon !== 'undefined' ? curated_places_yangcheon : []),
  ...(typeof curated_places_yeongdeungpo !== 'undefined' ? curated_places_yeongdeungpo : []),
  ...(typeof curated_places_yongsan !== 'undefined' ? curated_places_yongsan : [])
];
